name: Update user-agents dataset

on:
  push:
    branches: [ ci-test ]

jobs:
  update-agents:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: 🛎️ Checkout
      uses: actions/checkout@v4
      with:
        ref: ci-test

    - run: corepack enable
    
    - name: Setup Node 🐢
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: 📝 Updating user-agents dataset
      run: |
        curl -sS https://raw.githubusercontent.com/WebScrapingAPI/rand-user-agent/master/data/user-agents.json -o src/data/user-agents.json

    - name: 💾 Commit & push
      run: |
        git config user.name "Ahmed Rangel"
        git config user.email "ahmedrangel@outlook.com"
        git add src/data/user-agents.json
        git commit -m "chore: updated user-agents dataset"
        git push

    - name: Install
      run: |
        pnpm install
        
    - name: Generate Changelogen & Github Release
      run: |
        pnpm changelogen --release --push
        pnpm changelogen gh release --token ${{ secrets.GITHUB_TOKEN }}