name: Update user-agents dataset

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update-agents:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: 🛎️ Checkout
      uses: actions/checkout@v4

    - name: 📝 Updating user-agents dataset
      run: |
        curl -sS https://raw.githubusercontent.com/WebScrapingAPI/rand-user-agent/master/data/user-agents.json -o src/data/user-agents.json

    - name: 💾 Commit & push
      run: |
        git config user.name "ahmedrangel"
        git config user.email "ahmedrangel@outlook.com"
        git add src/data/user-agents.json
        git commit -m "chore: update user agent CI test"
        git push